#!/usr/bin/env bash
#pings an IP address passed as an argument

IP = "${1}"

FILENAME = $(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${FILENAME} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
